print("hello world")
print("WILLIAM QAS HESR")
print("works?")

print("steps for git")
print("git pull")
print("git add .")
print("git commit -m your message")
print("git push")
print("linux user bruh")